services:
  # Update this image
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: chronos-otp:1.0.0
    container_name: chronos-otp-web
    ports:
      - "7332:7332"
    environment:
      - NODE_ENV=production
      - PORT=7332
    env_file:
      - .env
    restart: unless-stopped

networks: {}

